### ISSUE TITLE
Command line tool vs homeassistant

### ISSUE THREAD

**Issue by clyra** [cherezov/orvibo#6] opened 2016-06-29 02:26 UTC
Hi,

Sorry, but I'm not sure if this is a orvibo library issue or not. But I just notice that if you use a orvibo "platform" switch inside homeassistant to control a socket, and also want to control another irda orvibo (using the shell, for example), one of then will fail complaining that there's already a socket open. Is there a way to have two instances of orvibo tools running?

**Comment by cherezov** [comment] 2016-07-02 11:13
This is a known issue. The root cause that all requests to Orvibo devices are initially made via broadcast to port 10000 and bind to current interface, thus next module instance can't bind to occupied interface and either discover device or sending request to exact device fails.
This is fixed in keep_connection branch, but hasn't merged yet for some reason. Since someone is care now, I'll merge it as soon as I can. Thank you!

**Comment by cherezov** [comment] 2016-07-02 12:02
Fix has just merged to 1.4 module version

**Comment by clyra** [comment] 2016-07-05 13:16
Hi,

great! but... how this works? Because I use to use the command line too. As
i understand the keep_connection would be useful only inside homeassistant,
or not?

On Sat, Jul 2, 2016 at 9:02 AM, Pavel notifications@github.com wrote:

> Fix has just merged to 1.4 module version
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/cherezov/orvibo/issues/6#issuecomment-230098507, or mute
> the thread
> https://github.com/notifications/unsubscribe/AEjpGrBsdwYYqRVsxBDHgky2WAgmHDtoks5qRlNlgaJpZM4JAtrk
> .

## 

Christian Lyra
PoP-PR/RNP

**Comment by cherezov** [comment] 2016-07-05 13:20
Right, keep_connection will be used only if you use the orvibo as python module.
The trick is in the socket creation function, which doesn't occupy broadcast port 10000 now and connects directly to the device if you want to send request.

**Closed as completed** 2016-07-19 10:39 UTC
Labels: bug
